version: '2'

services:
  php: 
    build: ./php
    links:
      - mysql
    volumes:
      - ./..:/var/www/source
    environment:
      - YII_DEBUG=true
      - YII_ENV=dev
      - DB_DSN=mysql:host=mysql;dbname=example
      - DB_USERNAME=example
      - DB_PASSWORD=example
    command: ["/var/www/wait-for-it.sh", "mysql:3306", "--", "/var/www/post-up.sh"]
 
  nginx:
    image: nginx
    links:
        - php
    volumes:
      - ./..:/var/www/source
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8888:80'

  mysql:
    image: mysql:5.6
    ports:
        - "3306:3306"
    expose:
        - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
