version: '2'

services:
  php: 
    build: ./php
    links:
      - mysql
    volumes:
      - ./..:/var/www/source
    environment:
      - YII_DEBUG=true
      - YII_ENV=dev
      - DB_DSN=mysql:host=mysql;dbname=example
      - DB_USERNAME=example
      - DB_PASSWORD=example

  nginx:
    image: nginx
    links:
        - php
    volumes:
      - ./..:/var/www/source
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8888:80'

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
